name: prevent-breaking-changes
trigger: before-file-modify
description: 防止破坏性代码修改的安全检查

## 关键修改警告

在修改以下文件前，必须进行额外检查：

### 1. package.json
- [ ] 确认依赖版本升级的必要性
- [ ] 检查是否有 breaking changes
- [ ] 运行 `npm install` 后测试关键功能

### 2. prisma/schema.prisma
- [ ] 确认数据库变更的必要性
- [ ] 创建对应的迁移脚本
- [ ] 确认旧数据迁移方案
- [ ] 在测试环境验证迁移

### 3. backend/src/config/*.ts
- [ ] 确认环境变量同步更新
- [ ] 更新 .env.example 文件
- [ ] 检查默认值是否安全

### 4. backend/src/middleware/auth.ts
- [ ] 安全相关变更必须双人审查
- [ ] 测试登录、权限验证流程

## 自动验证规则

### 修改 src/core/ 或 src/services/ 下的文件时
- 自动运行相关测试（如果有）
- 如果测试失败，阻止修改并报告

### 删除函数或导出时
- 使用 Grep 检查是否有其他文件引用
- 如果有引用，警告并要求确认

### 修改 API 路由时
- 检查前端代码是否需要同步更新
- 检查 API 文档是否需要更新

## 输出格式

当触发此 Hook 时，输出：

```
⚠️  [安全检查] 正在修改敏感文件: {filename}

检查项目：
{根据文件类型列出相关检查项}

✅ 所有检查通过，继续修改
或
❌ 发现问题，请确认后再继续
```
