/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatHeader: typeof import('./src/components/ChatHeader.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    RenameModal: typeof import('./src/components/RenameModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    StreamingProgress: typeof import('./src/components/StreamingProgress.vue')['default']
    TypingIndicator: typeof import('./src/components/TypingIndicator.vue')['default']
  }
}
